-- =========================================================
-- HR Attrition Analytics - SQL Analytics Scripts
-- This script contains queries designed for a SQL Server / PostgreSQL environment 
-- analyzing the Star Schema generated by the ETL pipeline.
-- =========================================================

-- 1. Attrition by Department and Job Role
SELECT 
    d.Department,
    d.JobRole,
    COUNT(f.EmployeeNumber) AS TotalEmployees,
    SUM(f.AttritionFlag) AS AttritionCount,
    ROUND(CAST(SUM(f.AttritionFlag) AS FLOAT) / COUNT(f.EmployeeNumber) * 100, 2) AS AttritionRate
FROM FactEmployeeAttrition f
JOIN DimDepartment d ON f.DepartmentID = d.DepartmentID
GROUP BY d.Department, d.JobRole
ORDER BY AttritionRate DESC;

-- 2. Overtime Risk Analysis
SELECT 
    f.OvertimeRisk,
    COUNT(f.EmployeeNumber) AS EmployeeCount,
    SUM(f.AttritionFlag) AS AttritionCount,
    ROUND(CAST(SUM(f.AttritionFlag) AS FLOAT) / COUNT(f.EmployeeNumber) * 100, 2) AS AttritionRate
FROM FactEmployeeAttrition f
GROUP BY f.OvertimeRisk
ORDER BY AttritionRate DESC;

-- 3. Salary vs Attrition Analysis (Income Bands)
SELECT 
    c.IncomeBand,
    COUNT(f.EmployeeNumber) AS TotalEmployees,
    SUM(f.AttritionFlag) AS AttritionCount,
    ROUND(CAST(SUM(f.AttritionFlag) AS FLOAT) / COUNT(f.EmployeeNumber) * 100, 2) AS AttritionRate
FROM FactEmployeeAttrition f
JOIN DimCompensation c ON f.EmployeeNumber = c.EmployeeNumber
GROUP BY c.IncomeBand
ORDER BY AttritionRate DESC;

-- 4. Satisfaction Risk Factors (Using CTE)
WITH SatisfactionMetrics AS (
    SELECT 
        s.SatisfactionCategory,
        COUNT(f.EmployeeNumber) AS TotalEmployees,
        SUM(f.AttritionFlag) AS AttritionCount
    FROM FactEmployeeAttrition f
    JOIN DimSatisfaction s ON f.SatisfactionID = s.SatisfactionID
    GROUP BY s.SatisfactionCategory
)
SELECT 
    SatisfactionCategory,
    TotalEmployees,
    AttritionCount,
    ROUND(CAST(AttritionCount AS FLOAT) / TotalEmployees * 100, 2) AS AttritionRate
FROM SatisfactionMetrics
ORDER BY AttritionRate DESC;

-- 5. High-Risk Employee Groups (Window Functions to Rank)
WITH RiskRanking AS (
    SELECT 
        e.EmployeeNumber,
        d.Department,
        d.JobRole,
        f.AttritionRiskScore,
        f.RetentionSegment,
        c.MonthlyIncome,
        RANK() OVER(PARTITION BY d.Department ORDER BY f.AttritionRiskScore DESC) AS RiskRank
    FROM FactEmployeeAttrition f
    JOIN DimEmployee e ON f.EmployeeNumber = e.EmployeeNumber
    JOIN DimDepartment d ON f.DepartmentID = d.DepartmentID
    JOIN DimCompensation c ON f.EmployeeNumber = c.EmployeeNumber
    WHERE f.Attrition = 'No' -- Only looking at current employees
)
SELECT 
    EmployeeNumber,
    Department,
    JobRole,
    AttritionRiskScore,
    RetentionSegment,
    MonthlyIncome
FROM RiskRanking
WHERE RiskRank <= 5 -- Top 5 highest risk employees per department
ORDER BY Department, RiskRank;

-- 6. Employee Tenure Trends
SELECT 
    f.TenureCategory,
    COUNT(f.EmployeeNumber) AS TotalEmployees,
    SUM(f.AttritionFlag) AS AttritionCount,
    ROUND(CAST(SUM(f.AttritionFlag) AS FLOAT) / COUNT(f.EmployeeNumber) * 100, 2) AS AttritionRate,
    AVG(f.YearsAtCompany) AS AvgYearsAtCompany
FROM FactEmployeeAttrition f
GROUP BY f.TenureCategory
ORDER BY AttritionRate DESC;

-- 7. Top Attrition Drivers (Aggregated Analysis)
SELECT 
    e.AgeGroup,
    c.IncomeBand,
    f.OvertimeRisk,
    f.RetentionSegment,
    SUM(f.AttritionFlag) AS TotalAttritions
FROM FactEmployeeAttrition f
JOIN DimEmployee e ON f.EmployeeNumber = e.EmployeeNumber
JOIN DimCompensation c ON f.EmployeeNumber = c.EmployeeNumber
GROUP BY e.AgeGroup, c.IncomeBand, f.OvertimeRisk, f.RetentionSegment
ORDER BY TotalAttritions DESC
LIMIT 10;
